version: "3"
services:
  mysql:
    image: mysql/mysql-server
    container_name: mysql_server
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
        - "3306:3306"
    volumes:
        - ./db/mysql_init:/docker-entrypoint-initdb.d   # 初期データ
        - ./db/mysql_data:/var/lib/mysql                # データ永続化
        - ./db/my.cnf:/etc/mysql/my.cnf                 # 設定
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: test_db
        TZ: 'Asia/Tokyo'
